python tools/supabase_ingest.py --phase upload --sku "EZ-A29 (private mold)" --category "cooling" --description "Fan Size: 120*120*25mm. Fan Speed: 800-1600±10% RPM. Fan Noise: 21±10%DBA. Fan Bearing: Fluid Bearing. Fan Airflow: 38±10%CFM. Fan Life: 30000hrs. Rated Voltage: 12V DC. Rated Current: 0.21±10%Amp. Light effect: ARGB. Interface: Small 5V 3Pin +4Pin PWM. mirror on the center."
python tools/supabase_ingest.py --phase upload --sku "EZ-A30 (private mold)" --category "cooling" --description "Fan Size: 120*120*25mm. Fan Speed: 800-1600±10% RPM. Fan Noise: 21±10%DBA. Fan Bearing: Fluid Bearing. Fan Airflow: 38±10%CFM. Fan Life: 30000hrs. Rated Voltage: 12V DC. Rated Current: 0.21±10%Amp. Light effect: ARGB. Interface: Small 5V 3Pin +4Pin PWM. aluminum plate +light ring in the center."
python tools/supabase_ingest.py --phase upload --sku "EZ-A31 (private mold)" --category "cooling" --description "Fan Size: 120*120*25mm. Fan Speed: 800-1600±10% RPM. Fan Noise: 21±10%DBA. Fan Bearing: Fluid Bearing. Fan Airflow: 38±10%CFM. Fan Life: 30000hrs. Rated Voltage: 12V DC. Rated Current: 0.21±10%Amp. Light effect: ARGB. Interface: Small 5V 3Pin +4Pin PWM. aluminum plate +light ring in the center."
python tools/supabase_ingest.py --phase upload --sku "EZ-A32 (private mold)" --category "cooling" --description "Fan Size: 120*120*25mm. Fan Speed: 800-1600±10% RPM. Fan Noise: 21±10%DBA. Fan Bearing: Fluid Bearing. Fan Airflow: 38±10%CFM. Fan Life: 30000hrs. Rated Voltage: 12V DC. Rated Current: 0.21±10%Amp. Light effect: ARGB. Interface: Small 5V 3Pin +4Pin PWM. aluminum plate +light ring in the center."

python tools/supabase_ingest.py --phase upload --sku "EZ-BB3" --category "cooling" --description "Modular Fans: sold as a set of three units. Unit Fan Size: 120*120*25mm."
python tools/supabase_ingest.py --phase upload --sku "EZ-BB2" --category "cooling" --description "Modular Fans: sold as a set of three units. Unit Fan Size: 120*120*25mm."
python tools/supabase_ingest.py --phase upload --sku "EZ-BB1" --category "cooling" --description "Modular Fans: sold as a set of three units. Unit Fan Size: 120*120*25mm."

python tools/supabase_ingest.py --phase upload --sku "EP-08 ARGB FAN SET" --category "cooling" --description "3pcs 6pin fans. A hub with 10-port fan position + 2-port light bar position. 21-Key Remote Controller. Motherboard Connection Cable+large 4 pin cable to PSU. Color box."
python tools/supabase_ingest.py --phase upload --sku "EF-16 ARGB FAN SET" --category "cooling" --description "3pcs 6pin fans. A hub with 10-port fan position + 2-port light bar position. 21-Key Remote Controller. Motherboard Connection Cable+large 4 pin cable to PSU. Color box."
python tools/supabase_ingest.py --phase upload --sku "EF-07 ARGB FAN SET" --category "cooling" --description "3pcs 6pin fans. A hub with 10-port fan position + 2-port light bar position. 21-Key Remote Controller. Motherboard Connection Cable+large 4 pin cable to PSU. Color box."
python tools/supabase_ingest.py --phase upload --sku "EZ-A18 ARGB FAN SET" --category "cooling" --description "3pcs 6pin fans. A hub with 10-port fan position + 2-port light bar position. 21-Key Remote Controller. Motherboard Connection Cable+large 4 pin cable to PSU. Color box."
python tools/supabase_ingest.py --phase upload --sku "EZ-A25 ARGB FAN SET" --category "cooling" --description "3pcs 6pin fans. A hub with 10-port fan position + 2-port light bar position. 21-Key Remote Controller. Motherboard Connection Cable+large 4 pin cable to PSU. Color box."
